spring:
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1037599166209-do066r04snv4ca9pf1u0pq88an9n233i.apps.googleusercontent.com
            client-secret: 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
          github:
            client-id: 5cf80a686aeb2a10873e
            client-secret: 4935a98f3cbbb91e8e3dbc01871efaf896cbf759

file:
  upload-dir: "src/main/resources/static/"
frontend:
  url: "http://localhost:3000"

